services:
  backend:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    restart: always
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

  frontend:
    build:
      context: ./ui
      args:
        - REACT_APP_BACKEND_URL=http://localhost:5000
    ports:
      - "3000:3000"
    volumes:
      - ./ui/public:/app/public
      - ./ui/src:/app/src
    depends_on:
      - backend
    restart: always
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
